lib: [
  "_build/install/default/lib/otp/META"
  "_build/install/default/lib/otp/dune-package"
  "_build/install/default/lib/otp/opam"
  "_build/install/default/lib/otp/otp.a"
  "_build/install/default/lib/otp/otp.cma"
  "_build/install/default/lib/otp/otp.cmi"
  "_build/install/default/lib/otp/otp.cmt"
  "_build/install/default/lib/otp/otp.cmti"
  "_build/install/default/lib/otp/otp.cmx"
  "_build/install/default/lib/otp/otp.cmxa"
  "_build/install/default/lib/otp/otp.ml"
  "_build/install/default/lib/otp/otp.mli"
]
libexec: [
  "_build/install/default/lib/otp/otp.cmxs"
]
doc: [
  "_build/install/default/doc/otp/LICENSE"
]
